# translate the v2c FACE_EXPRESSION node group (dumped by dumpgraph.py) into a GLSL function, node for node.
#   python3 nodes2glsl.py graph.json > face_expression.glsl.js
# Supported: GROUP_INPUT/OUTPUT, MATH, VECT_MATH (SCALE/ADD), SEPXYZ, COMBXYZ, TEX_IMAGE (linear, CLIP/EXTEND), MIX (RGBA, MIX).
import json, sys
g = json.load(open(sys.argv[1]))['FACE_EXPRESSION']; N = g['nodes']
links = {(l[2], l[3]): (l[0], l[1]) for l in g['links']}
IN = {'Socket_0': ('vec3', 'albedo'), 'Socket_1': ('vec3', 'vec3(faceUV, 0.0)'), 'Socket_2': ('float', 'faceMask'),
      'Socket_3': ('float', 'uFaceEyeR'), 'Socket_4': ('float', 'uFaceEyeL'), 'Socket_5': ('float', 'uFaceMouth'),
      'Socket_6': ('float', 'uFaceIrisR.x'), 'Socket_7': ('float', 'uFaceIrisR.y'), 'Socket_8': ('float', 'uFaceIrisL.x'),
      'Socket_9': ('float', 'uFaceIrisL.y'), 'Socket_10': ('float', 'uFaceIrisScale')}
SAMPLER = {'FACE_Base': 'tFaceBase', 'FACE_EyeUnder_R': 'tEyeUnderR', 'FACE_EyeUnder_L': 'tEyeUnderL', 'FACE_EyeOver_R': 'tEyeOverR',
           'FACE_EyeOver_L': 'tEyeOverL', 'FACE_Iris_R': 'tIrisR', 'FACE_Iris_L': 'tIrisL', 'FACE_MouthAtlas': 'tMouth'}
lines, done, ids = [], {}, {}
def vid(node):
    if node not in ids: ids[node] = f'n{len(ids)}'
    return ids[node]
def lit(v, typ):
    if typ == 'float': return f'{float(v):.6f}'
    v = list(v) + [0, 0, 0]; return f'vec3({float(v[0]):.6f}, {float(v[1]):.6f}, {float(v[2]):.6f})'
def conv(expr, src, dst):
    if src == dst: return expr
    if src == 'float' and dst == 'vec3': return f'vec3({expr})'
    if src == 'vec3' and dst == 'float': return f'dot({expr}, vec3(0.2126, 0.7152, 0.0722))'  # Blender colour->float
    raise ValueError((src, dst))
def inp(node, ident, typ):
    d = N[node]; spec = next(i for i in d['in'] if i[0] == ident)
    if (node, ident) in links:
        fn, fs = links[(node, ident)]; e, t = out(fn, fs); return conv(e, t, typ)
    return lit(spec[2], typ)
def out(node, sock):
    key = (node, sock)
    if key in done: return done[key]
    d = N[node]; t = d['type']; v = vid(node)
    if t == 'GROUP_INPUT':
        typ, e = IN[sock]; done[key] = (e, typ); return done[key]
    if t == 'MATH':
        a = inp(node, 'Value', 'float'); b = inp(node, 'Value_001', 'float') if any(i[0] == 'Value_001' for i in d['in']) else '0.0'
        op = d['op']
        e = {'MULTIPLY': f'{a} * {b}', 'SUBTRACT': f'{a} - {b}', 'ADD': f'{a} + {b}', 'DIVIDE': f'bdiv({a}, {b})',
             'GREATER_THAN': f'({a} > {b} ? 1.0 : 0.0)', 'LESS_THAN': f'({a} < {b} ? 1.0 : 0.0)', 'MAXIMUM': f'max({a}, {b})',
             'MINIMUM': f'min({a}, {b})', 'FLOOR': f'floor({a})', 'FLOORED_MODULO': f'bfmod({a}, {b})'}[op]
        if d.get('clamp'): e = f'clamp({e}, 0.0, 1.0)'
        lines.append(f'  float {v} = {e};'); done[key] = (v, 'float'); return done[key]
    if t == 'VECT_MATH':
        a = inp(node, 'Vector', 'vec3')
        if d['op'] == 'SCALE': e = f'{a} * {inp(node, "Scale", "float")}'
        elif d['op'] == 'ADD': e = f'{a} + {inp(node, "Vector_001", "vec3")}'
        else: raise ValueError(d['op'])
        lines.append(f'  vec3 {v} = {e};'); done[key] = (v, 'vec3'); return done[key]
    if t == 'SEPXYZ':
        a = inp(node, 'Vector', 'vec3')
        if (node, '_v') not in done: lines.append(f'  vec3 {v} = {a};'); done[(node, '_v')] = 1
        done[key] = (f'{v}.{sock.lower()}', 'float'); return done[key]
    if t == 'COMBXYZ':
        e = f'vec3({inp(node, "X", "float")}, {inp(node, "Y", "float")}, {inp(node, "Z", "float")})'
        lines.append(f'  vec3 {v} = {e};'); done[key] = (v, 'vec3'); return done[key]
    if t == 'TEX_IMAGE':
        if (node, '_s') not in done:
            uv = inp(node, 'Vector', 'vec3'); fn = 'texClip' if d['ext'] == 'CLIP' else 'texExtend'
            lines.append(f'  vec4 {v} = {fn}({SAMPLER[d["img"]]}, {uv}.xy);'); done[(node, '_s')] = 1
        done[key] = (f'{v}.rgb', 'vec3') if sock == 'Color' else (f'{v}.a', 'float'); return done[key]
    if t == 'MIX':
        assert d['dtype'] == 'RGBA' and d['blend'] == 'MIX', d
        f = inp(node, 'Factor_Float', 'float'); a = inp(node, 'A_Color', 'vec3'); b = inp(node, 'B_Color', 'vec3')
        lines.append(f'  vec3 {v} = mix({a}, {b}, clamp({f}, 0.0, 1.0));'); done[key] = (v, 'vec3'); return done[key]
    raise ValueError(t)
gout = next(n for n, d in N.items() if d['type'] == 'GROUP_OUTPUT')
res, typ = out(*links[(gout, 'Socket_11')])
body = '\n'.join(lines)
print(f'''// generated by LetMeGo-dschan/pipeline/nodes2glsl.py from v2c "FACE_EXPRESSION / 表情合成" ({len(N)} nodes) — do not edit by hand
export const FACE_EXPRESSION_GLSL = /* glsl */ `
uniform sampler2D tFaceBase, tEyeUnderR, tEyeUnderL, tEyeOverR, tEyeOverL, tIrisR, tIrisL, tMouth;
uniform float uFaceEyeR, uFaceEyeL, uFaceMouth, uFaceIrisScale;
uniform vec2 uFaceIrisR, uFaceIrisL;
float bdiv(float a, float b) {{ return b == 0.0 ? 0.0 : a / b; }}
float bfmod(float a, float b) {{ return b == 0.0 ? 0.0 : a - floor(a / b) * b; }}
vec4 texExtend(sampler2D t, vec2 uv) {{ return texture2D(t, clamp(uv, 0.0, 1.0)); }}
vec4 texClip(sampler2D t, vec2 uv) {{ return (uv.x < 0.0 || uv.y < 0.0 || uv.x > 1.0 || uv.y > 1.0) ? vec4(0.0) : texture2D(t, uv); }}
vec3 faceExpression(vec3 albedo, vec2 faceUV, float faceMask) {{
{body}
  return {res};
}}
`
''')
